### PR TITLE
Improved Support for Distributed Training

### PR DESCRIPTION
**Pull request by WardLT**
This PR adds support for ensuring that each replica has different training data during data-parallel training. This is accomplished by setting the same random seed for each `GraphSequence` and shifting the training data after shuffling.

### CODE REVIEW

**Comment by WardLT** [comment]
Note that this PR uses features from #3.

**Comment by pstjohn** [comment]
These are fantastic, thanks for the contribution! Should I merge this one and close #3?

**Comment by WardLT** [comment]
No problem. Thanks for making this open source! 😄

Sure, merging this and closing #3 would work for me.

**Comment by pstjohn** [comment]
Interesting, looks like github was smart enough to merge both :)

**Pull request merged**
